### ISSUE TITLE
Support css classes with escaped characters

### ISSUE THREAD

**Issue by joma74** [zignd/HTML-CSS-Class-Completion#127]
Tailwind's `w-1/4` does currently not get intellisensed to code completion. Code completion stops after the forward slash as in `w-1/`

As opposed to https://tailwindcss.com/docs/width/, this is really really :grinning: defined in CSS as
```css
...
.w-1\/4 {
  width: 25%;
}
...
```
