### ISSUE TITLE
not working with scss ?

### ISSUE THREAD

**Issue by craigcosmo** [zignd/HTML-CSS-Class-Completion#218]
```js
import './signup.scss'
export default class Signup extends React.Component {
	render() {
		return (
			<div className="signupComponent">
			</div>
		)
	}
}
```
**signup.scss**
```css
.signupComponent {
	.form {
		font-size: 12px;
	}
}

```

When I type `className="si` not happen, no autocomplete
